#pragma once

#include <cstdint>
#include <map>

enum CharacterVoice : uint32_t {
    VOICE_PAULIE,
    VOICE_SAM,
    VOICE_SALIERI,
    VOICE_TOMMY,
    VOICE_FRANK,
    VOICE_LUIGI,
    VOICE_RALPH,
    VOICE_VINCENZO,
    VOICE_MAN,
    VOICE_SALVATORE,
    VOICE_COP_0,
    VOICE_COM_1,
    VOICE_PORT_GUARD_0,
    VOICE_PORT_GUARD_1,
    VOICE_PORT_GUARD_2,
    VOICE_PORT_GUARD_3,
    VOICE_PORT_GUARD_4,
    VOICE_ENEMY_0,
    VOICE_ENEMY_1,
    VOICE_ENEMY_2,
    VOICE_ENEMY_3,
    VOICE_ENEMY_4,
    VOICE_HOOLIG,
    VOICE_SERGIO,
    VOICE_ENEMY_5,
    VOICE_JOE,
    VOICE_PED_MAN_0,
    VOICE_PED_MAN_1,
    VOICE_PED_MAN_2,
    VOICE_PED_WOMAN_0,
    VOICE_PED_WOMAN_1,
    VOICE_PED_WOMAN_2,
    VOICE_NO_VOICE,
    VOICE_LUCAS
};

enum Material : uint32_t {
    MAT_INVALID,
    MAT_ASPHALT,
    MAT_PAVEMENT,
    MAT_SIDEWALK,
    MAT_CONCRETE,
    MAT_GRASS,
    MAT_SAND,
    MAT_CLAY,
    MAT_GRAVEL,
    MAT_ROCK,
    MAT_RAILWAY_LINE,
    MAT_LEAVES,
    MAT_DO_NOT_USE,
    MAT_WOOD_0,
    MAT_WOOD_30,
    MAT_WOOD_70,
    MAT_PARQUET,
    MAT_MARBLE,
    MAT_CARPET,
    MAT_METAL_CONSTRUCTION,
    MAT_METAL_PLATE_0,
    MAT_METAL_PLATE_30,
    MAT_METAL_PLATE_70,
    MAT_DO_NOT_USE_2,
    MAT_GLASS,
    MAT_GLASS_UNBREAKABLE,
    MAT_DO_NOT_USE_3,
    MAT_WIRED_FENCE,
    MAT_WOODEN_FENCE,
    MAT_HEDGE,
    MAT_DO_NOT_USE_4,
    MAT_UNIVERSAL,
    MAT_DO_NOT_USE_5,
    MAT_BODY,
    MAT_PLASTER,
    MAT_JUNK,
    MAT_BRICKS,
    MAT_DO_NOT_USE_6,
    MAT_DEADLY_COLLISION,
    MAT_DESTRUCTIBLE_COLLISION,
    MAT_STRAW,
    MAT_BUTTER,
    MAT_SLIPPING_WATER,
    MAT_DIRTY_ROAD
};

enum PhysicsType : uint32_t {
    PT_STONE,
    PT_CRATE,
    PT_BARREL,
    PT_TRASH_BIN,
    PT_TRAFFIC_SIGN,
    PT_PAPER_BOX,
    PT_CONCRETE_T,
    PT_METAL_PLATE,
    PT_SMALL_WEAPON_0,
    PT_SMALL_WEAPON_1,
    PT_WOODEN_PLANK,
    PT_SMALL_METAL,
    PT_BIG_WEAPON,
    PT_CAR_LIGHT
};

enum Effect : uint32_t {
    EFF_BLOOD,
    EFF_HIT_STONEWALL,
    EFF_HIT_GROUND,
    EFF_HIT_METAL,
    EFF_HIT_WOOD,
    EFF_NIGHT_CHIMNEY_SMOKE,
    EFF_FIRE,
    EFF_EXPLOSION,
    EFF_MOLOTOV_EXPLOSION,
    EFF_FIRE_SMALL,
    EFF_EXPLOSION_BIG,
    EFF_MOLOTOV_FIRE,
    EFF_THOMPSON_MUZZLE_FLASH_DAY,
    EFF_THOMPSON_MUZZLE_FLASH_NIGHT,
    EFF_PISTOL_MUZZLE_FLASH_DAY,
    EFF_PISTOL_MUZZLE_FLASH_NIGHT,
    EFF_SHOTGUN_MUZZLE_FLASH_DAY,
    EFF_SHOTGUN_MUZZLE_FLASH_NIGHT,
    EFF_FIREWORKS,
    EFF_PENA,
    EFF_EXPLOSION_CAR,
    EFF_FIRE_FADING,
    EFF_FIRE_SMALL_FADING,
    EFF_PENA_VE_VANE,
    EFF_SMOKE_CIGARETTE,
    EFF_SMOKE_CIGARETTE_BREATH,
    EFF_CHCANI,
    EFF_BLITI,
    EFF_SMOKE_PARNIK,
    EFF_HIT_GRASS,
    EFF_VODA_PREHRADA,
    EFF_VODA_PREHRADA_DOLE,
    EFF_LISTI_ZE_STROMU,
    EFF_PRACH_MOTOREST,
    EFF_KOUR_RESTAURACE,
    EFF_DOLLARS,
    EFF_FONTANKA,
    EFF_ZBLUNK,
    EFF_SMOKE_SALIERY,
    EFF_LIGHTER,
    EFF_KREV_VRTULE,
    EFF_VODA_VEZENI,
    EFF_VODA_VEZENI_2,
    EFF_HIT_WATER,
    EFF_SMOKE_LOCO,
    EFF_STEAM_LOCO_2,
    EFF_CLUN,
    EFF_STEAM_LOCO,
    EFF_EXPLOSION_HOTEL,
    EFF_GASOLINE,
    EFF_SMOKE_COFFEE,
    EFF_EXPLOSION_HOTEL_2,
    EFF_EXPLOSION_MORELLO,
    EFF_DUST_MORELLO,
    EFF_KOLA_NA_VODE,
    EFF_SLOW_SMOKE,
    EFF_SPARK_CIG,
    EFF_FIRE_NO_SMOKE,
    EFF_SMOKE_CIGARETTE_BREATH_2,
    EFF_HORICI_BENZIN,
    EFF_FMV_LIGHTER,
    EFF_BLOOD_SAM_FMV,
    EFF_FMV_LOKO_SEC,
    EFF_FMV_LOKO_SEC_2,
    EFF_FMV_LOKO_0,
    EFF_FMV_LOKO_LOW,
    EFF_FMV_CHLADIC,
    EFF_FMV_EXPL_CISTERNA,
    EFF_FMV_LIGHTER_2,
    EFF_FMV_GASOLINE,
    EFF_DOUTNIK,
    EFF_KOUR_NA_LOKOMOTIVU_NESAHAT,
    EFF_VOL_DUST,
    EFF_HOVNA,
    EFF_FMV_CIGARETTE,
    EFF_DUST_FALL,
    EFF_KALUZ_CHUZE,
    EFF_FIRE_CIG,
    EFF_KOUR_LOD_DOPRAVA,
    EFF_FIREWORKS_1,
    EFF_FIREWORKS_2,
    EFF_FIREWORKS_3,
    EFF_FIREWORKS_4,
    EFF_VLNY,
    EFF_VLNY_BIG,
    EFF_VLNY_SMALL,
    EFF_FMV_SIRKA,
    EFF_HYDRANT,
    EFF_KYTKA_LISTY,
    EFF_HADICE,
    EFF_DYMOVNICE,
    EFF_FMV_PISTOL_MUZZLE_FLASH
};

enum ActorType : uint32_t {
    ACTOR_UNKNOWN = 0,
    ACTOR_HIDDEN = 1,
    ACTOR_PLAYER = 2,
    ACTOR_CAR = 4,
    ACTOR_DETECTOR = 5,
    ACTOR_DOOR = 6,
    ACTOR_RAILWAY = 8,
    ACTOR_VILLAOBJECT = 9,
    ACTOR_TRAFFIC = 12,
    ACTOR_PEDESTRIANS = 18,
    ACTOR_BRIDGE = 20,
    ACTOR_DOG = 21,
    ACTOR_AIRPLANE = 22,
    ACTOR_TURNOUT = 24,
    ACTOR_PUMPER = 25,
    ACTOR_ENEMY = 27,
    ACTOR_RACECAMERA = 28,
    ACTOR_WAGON = 30,
    ACTOR_CLOCK = 34,
    ACTOR_PHYSICAL = 35,
    ACTOR_TRUCK = 36
};

static std::map<ActorType, std::string> g_ActorTypeString = {{ACTOR_UNKNOWN, "Unknown"},
                                                           {ACTOR_HIDDEN, "Hidden"},
                                                           {ACTOR_PLAYER, "Player"},
                                                           {ACTOR_CAR, "Car"},
                                                           {ACTOR_DETECTOR, "Detector"},
                                                           {ACTOR_DOOR, "Door"},
                                                           {ACTOR_RAILWAY, "Railway"},
                                                           {ACTOR_VILLAOBJECT, "Villa Object"},
                                                           {ACTOR_TRAFFIC, "Traffic"},
                                                           {ACTOR_PEDESTRIANS, "Pedestrians"},
                                                           {ACTOR_BRIDGE, "Bridge"},
                                                           {ACTOR_DOG, "Dog"},
                                                           {ACTOR_AIRPLANE, "Airplane"},
                                                           {ACTOR_TURNOUT, "Turnout"},
                                                           {ACTOR_PUMPER, "Pumper"},
                                                           {ACTOR_ENEMY, "Human"},
                                                           {ACTOR_RACECAMERA, "Race Camera"},
                                                           {ACTOR_WAGON, "Wagon"},
                                                           {ACTOR_CLOCK, "Clock"},
                                                           {ACTOR_PHYSICAL, "Physical"},
                                                           {ACTOR_TRUCK, "Truck"}};